### ISSUE TITLE
Possibly Integrate SMTP.js to allow sending serverless emails

### ISSUE THREAD

**Issue by craitose** [cenfun/monocart-reporter-examples#5]
Hi, is it possible to modify  send-email.js by integrating or emulating the npm package SMTP.js in order to allow sending report emails without an email or server?
There is limited documentation but this user claims to have sent emails from the browser with this package.
[SMTP.js](https://dev.to/scofieldidehen/smtpjs-send-email-without-a-server-from-the-browser-2oo2)

**Comment by cenfun** [comment]
Thanks for the suggestion. But I can't find it in npmjs.com: https://www.npmjs.com/search?q=SMTP.js
In fact, you can ignore the officially provided 'capability.sendEmail', and replace it with the `SMTP.js` you mentioned.

**Comment by craitose** [comment]
Thank, I will try to make the changes and report back

**Comment by craitose** [comment]
It is not possible to do , as emails are being rejected
